import { Layout } from "nextra-theme-blog";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Layout>{children}</Layout>
    </div>
  );
}
